window.FOOD_DATABASE = {
  1: [
    {
      id: "wholegrainBread",
      name: "Täisteraleib",
      image: "Cereal and bread/Black bread 1.png",
      points: 15,
      healthy: true,
      tag: "Aeglased süsivesikud",
    },
    {
      id: "porridge",
      name: "Kaerahelbepuder",
      image: "Cereal and bread/Porridge 1.png",
      points: 15,
      healthy: true,
      tag: "Süsivesikud & Magneesium",
    },
    {
      id: "whiteBread",
      name: "Sai",
      image: "Cereal and bread/Bread 1.png",
      points: 5,
      healthy: true,
      tag: "Kiired süsivesikud",
    },
    {
      id: "meatPie",
      name: "Lihapirukas",
      image: "Cereal and bread/pie.png",
      points: -5,
      healthy: false,
      tag: "Rasvad & Süsivesikud",
    },
    {
      id: "sweetCereal",
      name: "Šokolaadikrõbinad",
      image: "Cereal and bread/Cereal 1.png",
      points: -5,
      healthy: false,
      tag: "Suhkur",
    },
    {
      id: "energyDrink",
      name: "Energiajook",
      image: "Fast food/Energy drink.png",
      points: -15,
      healthy: false,
      tag: "Liigne suhkur & Kofeiin",
    },
    {
      id: "fruitMuesli",
      name: "Müsli puuviljadega",
      image: "Cereal and bread/Cereal 1.png",
      points: 10,
      healthy: true,
      tag: "Kiudained & Energia",
    },
    {
      id: "croissant",
      name: "Croissant/Sarvesai",
      image: "Cereal and bread/Bread 1.png",
      points: -5,
      healthy: false,
      tag: "Rasvad & Kiired süsivesikud",
    },
    {
      id: "syrupPancakes",
      name: "Pannkoogid siirupiga",
      image: "Sweets/Cake.png",
      points: -5,
      healthy: false,
      tag: "Suhkur",
    },
    {
      id: "wholegrainTortilla",
      name: "Täisteratortilja",
      image: "Cereal and bread/Bread 1.png",
      points: 10,
      healthy: true,
      tag: "Aeglased süsivesikud",
    },
  ],
  2: [
    {
      id: "cucumber",
      name: "Kurk",
      image: "Vegetables/Cucumber.png",
      points: 15,
      healthy: true,
      tag: "Vitamiinid & Vesi",
    },
    {
      id: "tomato",
      name: "Tomat",
      image: "Vegetables/Tomato.png",
      points: 15,
      healthy: true,
      tag: "Lükopeen & Vitamiin C",
    },
    {
      id: "broccoli",
      name: "Brokkoli",
      image: "Vegetables/Broccoli.png",
      points: 15,
      healthy: true,
      tag: "Kiudained & Vitamiin K",
    },
    {
      id: "bananaLunch",
      name: "Banaan",
      image: "Fruits/Banana.png",
      points: 15,
      healthy: true,
      tag: "Kaalium & Energia",
    },
    {
      id: "appleLunch",
      name: "Õun",
      image: "Fruits/Apple.png",
      points: 15,
      healthy: true,
      tag: "Vitamiinid",
    },
    {
      id: "fries",
      name: "Friikartulid",
      image: "Fast food/French fries.png",
      points: -10,
      healthy: false,
      tag: "Küllastunud rasvad",
    },
    {
      id: "sodaLunch",
      name: "Limonaad",
      image: "Fast food/Cola.png",
      points: -15,
      healthy: false,
      tag: "Liigne suhkur",
    },
    {
      id: "carrot",
      name: "Porgand",
      image: "Vegetables/Cucumber.png",
      points: 15,
      healthy: true,
      tag: "Beetakaroteen & Kiudained",
    },
    {
      id: "fruitSmoothie",
      name: "Smuuti",
      image: "Fruits/Banana.png",
      points: 10,
      healthy: true,
      tag: "Vitamiinid & Energia",
    },
    {
      id: "vegetableSalad",
      name: "Aedviljasalat",
      image: "Vegetables/Tomato.png",
      points: 15,
      healthy: true,
      tag: "Vitamiinid & Kiudained",
    },
  ],
  3: [
    {
      id: "chickenFillet",
      name: "Kanafillee",
      image: "Fish and meat/Chicken.png",
      points: 15,
      healthy: true,
      tag: "Kvaliteetne valk",
    },
    {
      id: "fishProtein",
      name: "Kala",
      image: "Fish and meat/Fish.png",
      points: 15,
      healthy: true,
      tag: "Oomega-3 rasvhapped & Valk",
    },
    {
      id: "eggProtein",
      name: "Muna",
      image: "Eggs and Dairy/Egg 1.png",
      points: 15,
      healthy: true,
      tag: "Valk & Koliin",
    },
    {
      id: "cheese",
      name: "Juust",
      image: "Eggs and Dairy/Cheese 1.png",
      points: 10,
      healthy: true,
      tag: "Kaltsium & Valk",
    },
    {
      id: "yogurtProtein",
      name: "Jogurt",
      image: "Eggs and Dairy/Yogurt 1.png",
      points: 15,
      healthy: true,
      tag: "Probiootikumid & Kaltsium",
    },
    {
      id: "sausages",
      name: "Viinerid",
      image: "Fish and meat/Sausages.png",
      points: -5,
      healthy: false,
      tag: "Sool & Säilitusained",
    },
    {
      id: "nuggets",
      name: "Kananagitsad",
      image: "Fast food/Nuggets.png",
      points: -10,
      healthy: false,
      tag: "Rasvad & Sool",
    },
    {
      id: "curd",
      name: "Kohupiim",
      image: "Eggs and Dairy/Yogurt 1.png",
      points: 15,
      healthy: true,
      tag: "Valk & Kaltsium",
    },
    {
      id: "greekYogurt",
      name: "Kreeka jogurt",
      image: "Eggs and Dairy/Yogurt 1.png",
      points: 15,
      healthy: true,
      tag: "Probiootikumid & Valk",
    },
    {
      id: "peanutButter",
      name: "Pähklivõi",
      image: "Fruits/Cocount.png",
      points: 10,
      healthy: true,
      tag: "Tervislikud rasvad & Valk",
    },
  ],
  4: [
    {
      id: "nutsSnack",
      name: "Pähklid",
      image: "Fruits/Cocount.png",
      points: 15,
      healthy: true,
      tag: "Tervislikud rasvad",
    },
    {
      id: "chocolateSnack",
      name: "Šokolaad",
      image: "Sweets/Chocolate.png",
      points: 0,
      healthy: null,
      tag: "Kiire energia",
    },
    {
      id: "burger",
      name: "Burger",
      image: "Fast food/Burgar.png",
      points: -10,
      healthy: false,
      tag: "Liigne rasv",
    },
    {
      id: "pizza",
      name: "Pitsa",
      image: "Fast food/Pizza 1.png",
      points: -10,
      healthy: false,
      tag: "Liigne sool & rasv",
    },
    {
      id: "chips",
      name: "Krõpsud",
      image: "Fast food/Chips.png",
      points: -15,
      healthy: false,
      tag: "Transrasvad & Sool",
    },
    {
      id: "cakeSnack",
      name: "Kook",
      image: "Sweets/Cake.png",
      points: -10,
      healthy: false,
      tag: "Suhkur",
    },
    {
      id: "iceCream",
      name: "Jäätis",
      image: "Sweets/Cake.png",
      points: -10,
      healthy: false,
      tag: "Suhkur & Rasvad",
    },
    {
      id: "gummyFruit",
      name: "Mahlakommid",
      image: "Sweets/Chocolate.png",
      points: -10,
      healthy: false,
      tag: "Lisatud suhkur",
    },
    {
      id: "driedFruit",
      name: "Kuivatatud puuviljad",
      image: "Fruits/Apple.png",
      points: 10,
      healthy: true,
      tag: "Kiudained & Looduslik suhkur",
    },
    {
      id: "popcorn",
      name: "Popkorn",
      image: "Fast food/Chips.png",
      points: 0,
      healthy: null,
      tag: "Neutraalne vahepala",
    },
  ],
};

window.DAILY_TASKS = {
  1: {
    title: "1. Korrus: Hommikusöök",
    task: "Ees ootab eksam! Vali toidud pikaajaliseks fookuseks.",
  },
  2: {
    title: "2. Korrus: Lõunasöök",
    task: "Vajad taastumiseks vitamiine ja kiudaineid.",
  },
  3: {
    title: "3. Korrus: Õhtuoode & Trenn",
    task: "Trennieelne energia! Lihased vajavad valku ja kaltsiumi.",
  },
  4: {
    title: "4. Korrus: Päeva lõpp & Tipp",
    task: "Vahepalad ja maiustused. Mäleta mõõdukuse reeglit!",
  },
};
